pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            url = uri('https://maven.pkg.github.com/Students-buisness-incubator-of-TUSUR/track-me-platform')
            credentials {
                username = providers.gradleProperty('gpr.user').getOrElse(System.getenv('GITHUB_ACTOR') ?: '')
                password = providers.gradleProperty('gpr.key').getOrElse(System.getenv('GITHUB_TOKEN') ?: '')
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'trackme'

def includeProject = { String projectPath, String projectDir ->
    if (file(projectDir).isDirectory()) {
        include projectPath
        project(projectPath).projectDir = file(projectDir)
    }
}

includeProject(':backend', 'apps/backend')
includeProject(':trackme-gateway', 'apps/trackme-gateway')
includeProject(':trackme-sso', 'services/trackme-sso')
includeProject(':meeting-service', 'services/meeting-service')
includeProject(':telegram-service', 'services/telegram-service')
