spring:
  profiles:
    active: development
  application:
    name: trackme-sso
  session:
    timeout: 1800                 # Время жизни сессии (в секундах)
    redis:
      flush-mode: on_save         # Указываем, когда изменения сеанса записываются в хранилище (immediate или on_save)
      namespace: trackme-sso:session    # Пространство имен для ключей, используемых для хранения сессий.
      save-mode: on_set_attribute # Определяет в какой момент происходит сохранение изменений сессии (on_set_attribute, on_get_attribute, always)
  data:
    redis: # Настраиваем подключение к Redis
      client-type: lettuce        # Указываем тип клиента Redis (jedis или lettuce)
      database: 1                 # Указываем номер БД Redis
      host: 127.0.0.1             # Хост подключения
      port: 6379                  # Порт подключения
      password: trackme-redis    # Пароль подключения
      username: trackme-redis

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        multiple-issuers-allowed: true
      client:
        provider:
          track-me:
            issuer-uri: http://localhost:9000
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:project-place}
    username: ${DB_USERNAME:project-place}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/project-place}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-track-me-sso"
      register-mbeans: true
  liquibase:
    enabled: true
    change-log: classpath:db.changelog.yaml
    contexts: dev prod
    default-schema: sso
server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

app:
  swagger:
    auth-types:
      auth-header-enabled: true
      client-credentials-enabled: true
      authorization-code-enabled: true
    auth-oauth:
      token-url: http://localhost:9000/oauth2/token
      authorization_url: http://localhost:9000/oauth2/authorize
      refresh-url: http://localhost:9000/oauth2/token

---
spring:
  config:
    activate:
      on-profile: production
  liquibase:
    contexts: prod

---
spring:
  config:
    activate:
      on-profile: development
  liquibase:
    contexts: prod, dev