server:
  port: 9000

spring:
  application:
    name: trackme-sso
  mvc:
    static-path-pattern: /static/**
  mail:
    host: ${MAIL_HOST:smtp.tusur.ru}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:startup-poligon@tusur.ru}
    password: ${MAIL_PASSWORD:paKLRD9CvSrv2pXPSAOH}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  config:
    import:
      - application-data.yaml
      - application-security.yaml

logging:
  level:
    org.springframework.security: trace

app:
  swagger:
    auth-types:
      auth-header-enabled: true
      client-credentials-enabled: true
      authorization-code-enabled: true
    auth-oauth:
      token-url: http://localhost:9000/oauth2/token
      authorization_url: http://localhost:9000/oauth2/authorize
      refresh-url: http://localhost:9000/oauth2/token
  api-url: http://127.0.0.1:8081/sso
  mail:
    from: ${MAIL_FROM:startup-poligon@tusur.ru}
    subject: ${MAIL_SUBJECT:TrackMe SSO}


registration-store:
  cookie-name: trackme-sso-temporary-session
  cookie-domain: localhost
  cookie-max-age: 1h