server:
  port: 9000

spring:
  application:
    name: trackme-sso
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    org.springframework.security: trace

app:
  swagger:
    auth-types:
      auth-header-enabled: true
      client-credentials-enabled: true
      authorization-code-enabled: true
    auth-oauth:
      token-url: http://localhost:9000/oauth2/token
      authorization_url: http://localhost:9000/oauth2/authorize
      refresh-url: http://localhost:9000/oauth2/token
  api-url: http://127.0.0.1:8081/sso