spring:
  profiles:
    active: development
  application:
    name: track-me-sso
  security:
    oauth2:
      authorizationserver:
        client:
          track-me:
            registration:
              client-id: track-me-client
              client-secret: "$2a$12$MauKt/v9PcELn2RbIktW0etKpx9KxUHnnZWRMLG/Tk2RzMMEwkEN."
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - client_credentials
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8081/login/oauth2/code/track-me-as
              scopes: openid, profile
            require-authorization-consent: true
        issuer: http://localhost:9000
        multiple-issuers-allowed: true
      client:
        provider:
          track-me:
            issuer-uri: http://localhost:9000
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:project-place}
    username: ${DB_USERNAME:project-place}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/project-place}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-track-me-sso"
      register-mbeans: true
  liquibase:
    enabled: true
    change-log: classpath:db.changelog.yaml
    contexts: dev prod
    default-schema: sso
server:
  port: 9000

logging:
  level:
    org.springframework.security: trace


---
spring:
  config:
    activate:
      on-profile: production
  liquibase:
    contexts: prod

---
spring:
  config:
    activate:
      on-profile: development
  liquibase:
    contexts: prod, dev