plugins {
    id 'java'
    id 'war'
    id 'org.springframework.boot' version '3.4.0'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'com.github.node-gradle.node' version '7.0.2'
}

repositories {
    mavenCentral()
}

version = '1.0.0'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.liquibase:liquibase-core'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.session:spring-session-jdbc'
    implementation 'org.springframework.session:spring-session-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    compileOnly 'org.projectlombok:lombok'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.springframework.boot:spring-boot-docker-compose'
    runtimeOnly 'org.postgresql:postgresql'

    annotationProcessor 'org.projectlombok:lombok'

    implementation project(':commons')
}

test {
    useJUnitPlatform()
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDirs = ['src/main/resources', 'database', 'frontend']
        }
    }
}

springBoot {
    buildInfo()
}


node {
    version = '23.10.0'
    npmVersion = '10.9.2'
    download = true
    nodeProjectDir = file("${projectDir}/frontend")
}

tasks.register('installReact', NpmTask) {
    args = ['install']
    workingDir = file("${projectDir}/frontend")
}

tasks.register('buildReact', NpmTask) {
    args = ['run', 'build']
    workingDir = file("${projectDir}/frontend")
    dependsOn installReact // Зависит от установки зависимостей
}

tasks.register('copyReactBuild', Copy) {
    from file("${projectDir}/frontend/build/static") // Путь к собранному React приложению
    into 'src/main/resources/static'
    dependsOn buildReact // Зависит от сборки React
}

tasks.register('copyIndexToTemplates', Copy) {
    from file("${projectDir}/frontend/build/index.html") // Путь к index.html
    into 'src/main/resources/templates'
    dependsOn copyReactBuild // Зависит от копирования React сборки
}

processResources.dependsOn copyIndexToTemplates