server:
  port: 8081


spring:
  application:
    name: track-me-gateway
  cloud:
    gateway:
      routes:
        - id: track-me-backend
          uri: http://localhost:8080
          predicates:
            - Path=/backend/**
          filters:
            - TokenRelay
            - StripPrefix=1
        - id: track-me-sso
          uri: http://localhost:9000
          predicates:
            - Path=/sso/**
          filters:
            - TokenRelay
            - StripPrefix=1
  security:
    oauth2:
      client:
        registration:
          track-me-client:
            client-id: track-me-client
            client-secret: password
            provider: track-me-client
            client-name: TrackMe SSO
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
          github:
            client-id: ${GITHUB_CLIENT_ID:Ov23li9LSVY7JkqnAVdR}
            client-secret: e4836cdd4fe5e48481903637b3f53c9a60f7e5b8
        provider:
          track-me-client:
            issuer-uri: http://localhost:9000
logging:
  level:
    org.springframework.security: trace

springdoc:
  swagger-ui:
    enabled: true
    doc-expansion: none
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    urls:
      - name: TrackMe SSO
        url: http://127.0.0.1:8081/sso/v3/api-docs
      - name: TrackMe Backend
        display-name: TrackMe Backend
        url: http://127.0.0.1:8081/backend/v3/api-docs
    with-credentials: true
    use-root-path: true
    csrf:
      enabled: true
  api-docs:
    enabled: true