server:
  port: 8081


spring:
  application:
    name: track-me-gateway
  cloud:
    gateway:
      routes:
        - id: track-me-backend
          uri: http://localhost:8080
          predicates:
            - Path=/backend/**
          filters:
            - TokenRelay
            - StripPrefix=1
        - id: track-me-sso
          uri: http://localhost:9000
          predicates:
            - Path=/sso/**
          filters:
            - TokenRelay
            - StripPrefix=1
  security:
    oauth2:
      client:
        registration:
          track-me-client:
            client-id: track-me-client
            client-secret: password
            provider: track-me-client
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          track-me-client:
            issuer-uri: http://localhost:9000
logging:
  level:
    org.springframework.security: trace

springdoc:
  swagger-ui:
    enabled: true
    use-root-path: true
    doc-expansion: none
    disable-swagger-default-url: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    urls:
      - name: TrackMe SSO Service
        url: http://localhost:9000/v3/api-docs
      - name: TrackMe Backend Service
        display-name: TrackMe Backend Service
        url: http://localhost:8080/v3/api-docs
  api-docs:
    enabled: true