name: check-changes.yml
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes in backend
        id: backend
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '^apps/backend/' || exit 1

      - name: Check for changes in frontend
        id: frontend
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '^apps/frontend/' || exit 1

      - name: Run tests for backend
        if: steps.backend.outcome == 'success'
        run: ./gradlew :apps:backend:test